In [62]:
! pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.2.4)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
import  pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error ,r2_score

In [64]:
df=pd.read_csv("advertising-dataset.csv")
df

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
199   38.2    3.7       13.8    7.6
200   94.2    4.9        8.1   14.0
201  177.0    9.3        6.4   14.8
202  283.6   42.0       66.2   25.5
203  232.1    8.6        8.7   18.4

[204 rows x 4 columns]

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         204 non-null    float64
 1   Radio      203 non-null    float64
 2   Newspaper  202 non-null    float64
 3   Sales      204 non-null    float64
dtypes: float64(4)
memory usage: 6.5 KB

In [66]:
df.describe()

               TV       Radio   Newspaper       Sales
count  204.000000  203.000000  202.000000  204.000000
mean   147.096569   22.919212   30.516337   15.031863
std     85.005037   15.000253   21.669154    5.278091
min      0.700000    0.000000    0.300000    1.600000
25%     75.000000    9.450000   12.825000   10.875000
50%    149.800000   22.300000   25.600000   15.750000
75%    218.425000   36.400000   44.900000   18.925000
max    296.400000   49.600000  114.000000   27.000000

In [67]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [68]:
df.tail()

        TV  Radio  Newspaper  Sales
199   38.2    3.7       13.8    7.6
200   94.2    4.9        8.1   14.0
201  177.0    9.3        6.4   14.8
202  283.6   42.0       66.2   25.5
203  232.1    8.6        8.7   18.4

## Handle Missing Value

In [69]:
df.isnull().sum()

TV           0
Radio        1
Newspaper    2
Sales        0
dtype: int64

In [70]:
df['Radio']

0      37.8
1      39.3
2      45.9
3      41.3
4      10.8
       ...
199     3.7
200     4.9
201     9.3
202    42.0
203     8.6
Name: Radio, Length: 204, dtype: float64

In [71]:
df.fillna(df['Radio'].mean(), inplace=True)

In [72]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

## Handle Duplicate Data

In [73]:

# ! Check How many Duplicate value is present
df.duplicated().sum()

np.int64(3)

In [74]:

# ! Find Who are Duplicate value
duplicates = df[df.duplicated()]
print(duplicates)

        TV  Radio  Newspaper  Sales
158  149.8    1.3       24.3   10.1
174  149.8    1.3       24.3   10.1
180  149.8    1.3       24.3   10.1

In [77]:
df_no_duplicate=df.drop_duplicates()
print(df_no_duplicate)

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
199   38.2    3.7       13.8    7.6
200   94.2    4.9        8.1   14.0
201  177.0    9.3        6.4   14.8
202  283.6   42.0       66.2   25.5
203  232.1    8.6        8.7   18.4

[201 rows x 4 columns]

In [ ]:

# ! Check Duplicates are deleted ?? and Before and after 
print("Before:", len(df))
print("After:", len(df.drop_duplicates()))
print("Deleted:", len(df) - len(df.drop_duplicates()))

Before: 204
After: 201
Deleted: 3

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
199   38.2    3.7       13.8    7.6
200   94.2    4.9        8.1   14.0
201  177.0    9.3        6.4   14.8
202  283.6   42.0       66.2   25.5
203  232.1    8.6        8.7   18.4

[204 rows x 4 columns]

In [82]:
# x=df[['Newspaper','TV','Radio']]
# y=df[['Sales']]
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2 , random_state=42)
# model=LinearRegression()
# model.fit(x_train,y_train)
# y_pred=model.predict(x_test)
# mse=mean_squared_error(y_test,y_pred)
# r2=r2_score(y_test,y_pred)
# print(f"Mean Squared Erroe: {mse}")
# print(f"R^2 Score: {r2}")
# predicted_sale=model.predict([[2021]])
# print(f"Predicted Sales for 2021: {predicted_sale}")