In [58]:
import pandas as pd
data={
    "Name": ["Alice","Bob","Charlie"],
    "Age":[20,34,56],
    "City":["Indore","Newyork","Chicago"]
    }

In [59]:
df=pd.DataFrame(data) 
df

      Name  Age     City
0    Alice   20   Indore
1      Bob   34  Newyork
2  Charlie   56  Chicago

In [60]:
df[['Name','Age']] # Select Indiviual Columns

      Name  Age
0    Alice   20
1      Bob   34
2  Charlie   56

In [61]:
# Find Row detail of indexing 1 
# ! Work with Indexing
df.loc[1]

Name        Bob
Age          34
City    Newyork
Name: 1, dtype: object

In [62]:

df.iloc[1]

Name        Bob
Age          34
City    Newyork
Name: 1, dtype: object

In [63]:
# Show dataframe
df

      Name  Age     City
0    Alice   20   Indore
1      Bob   34  Newyork
2  Charlie   56  Chicago

In [64]:
# Change Indexing 0,1,2 to given index
df.index=['winner','first_runner_Up','second_runner_up']

In [65]:
df

                     Name  Age     City
winner              Alice   20   Indore
first_runner_Up       Bob   34  Newyork
second_runner_up  Charlie   56  Chicago

In [66]:
df.iloc[1]
# select index 1 for show row 1

Name        Bob
Age          34
City    Newyork
Name: first_runner_Up, dtype: object

In [67]:
df.loc['first_runner_Up']
# select label first_runner_Up for row 1

Name        Bob
Age          34
City    Newyork
Name: first_runner_Up, dtype: object

In [68]:

# ! Python specific  
del df['City'] 
#  Delete City

In [ ]:

# ! Pandas Method
df=df.drop(['Age'],axis=1)
# axis

In [80]:
df

                     NAME NAME UPPER
winner              Alice      ALICE
first_runner_Up       Bob        BOB
second_runner_up  Charlie    CHARLIE

In [72]:

# ! Rename Col Name
new_col={
    'Name':'NAME',
}
df.rename(columns=new_col,inplace=True)

df

                     NAME
winner              Alice
first_runner_Up       Bob
second_runner_up  Charlie

In [ ]:

# ! Uppercase for Name Column
uppercase_value=df['NAME'].str.upper()
uppercase_value

winner                ALICE
first_runner_Up         BOB
second_runner_up    CHARLIE
Name: NAME, dtype: object

In [78]:
df['NAME UPPER']=df['NAME'].str.upper()
df

                     NAME NAME UPPER
winner              Alice      ALICE
first_runner_Up       Bob        BOB
second_runner_up  Charlie    CHARLIE

Performing Data Analysis Over Some Random Data

In [87]:
data=pd.read_csv('data.csv')
data

      Name   Age     City    Position
0    Divya  23.0   Indore     Manager
1    Rohan  24.0    Dewas   Developer
2  Charlie   NaN  NewYork     Analyst
3      Bob  20.0  Chicago    Designer
4    Alice  17.0  Phoenix  Consultant

In [89]:

# ! Handling Missing Value  
# 1.isnull() for check 
data.isnull().sum()

Name        0
Age         1
City        0
Position    0
dtype: int64

In [ ]:

#!Checking Notnull data 
data.notnull().sum()

Name        5
Age         4
City        5
Position    5
dtype: int64

In [ ]:
data.dropna(axis=1)

Instead of dropping just fill values with actual values

In [ ]:
data.fillna(0,inplace=True)
data

      Name   Age     City    Position
0    Divya  23.0   Indore     Manager
1    Rohan  24.0    Dewas   Developer
2  Charlie   0.0  NewYork     Analyst
3      Bob  20.0  Chicago    Designer
4    Alice  17.0  Phoenix  Consultant

In [95]:
data

      Name   Age     City    Position
0    Divya  23.0   Indore     Manager
1    Rohan  24.0    Dewas   Developer
2  Charlie   0.0  NewYork     Analyst
3      Bob  20.0  Chicago    Designer
4    Alice  17.0  Phoenix  Consultant

In [101]:
data.fillna(data['Age'].mean(),inplace=True)
data

      Name   Age     City    Position
0    Divya  23.0   Indore     Manager
1    Rohan  24.0    Dewas   Developer
2  Charlie   0.0  NewYork     Analyst
3      Bob  20.0  Chicago    Designer
4    Alice  17.0  Phoenix  Consultant

In [ ]:
# Statistical Data
data.describe()

             Age
count   5.000000
mean   16.800000
std     9.782638
min     0.000000
25%    17.000000
50%    20.000000
75%    23.000000
max    24.000000

In [ ]:
# Descriptive Statistics of the dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      object
 1   Age       5 non-null      float64
 2   City      5 non-null      object
 3   Position  5 non-null      object
dtypes: float64(1), object(3)
memory usage: 292.0+ bytes

In [ ]:
# 1st 2 data
data.head(2)

    Name   Age    City   Position
0  Divya  23.0  Indore    Manager
1  Rohan  24.0   Dewas  Developer

In [ ]:
# last 2 data
data.tail(2)

    Name   Age     City    Position
3    Bob  20.0  Chicago    Designer
4  Alice  17.0  Phoenix  Consultant