In [39]:
! pip install pandas

Requirement already satisfied: pandas in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:
import pandas as pd
data={
    "Name": ["Alice","Bob","Charlie"],
    "Age":[20,34,56],
    "City":["Indore","Newyork","Chicago"]
    }

In [41]:
df=pd.DataFrame(data) 
df

      Name  Age     City
0    Alice   20   Indore
1      Bob   34  Newyork
2  Charlie   56  Chicago

In [42]:
df[['Name','Age']] # Select Indiviual Columns

      Name  Age
0    Alice   20
1      Bob   34
2  Charlie   56

In [43]:
# Find Row detail of indexing 1 
# ! Work with Indexing
df.loc[1]

Name        Bob
Age          34
City    Newyork
Name: 1, dtype: object

In [44]:

df.iloc[1]

Name        Bob
Age          34
City    Newyork
Name: 1, dtype: object

In [45]:
# Show dataframe
df

      Name  Age     City
0    Alice   20   Indore
1      Bob   34  Newyork
2  Charlie   56  Chicago

In [46]:
# Change Indexing 0,1,2 to given index
df.index=['winner','first_runner_Up','second_runner_up']

In [47]:
df

                     Name  Age     City
winner              Alice   20   Indore
first_runner_Up       Bob   34  Newyork
second_runner_up  Charlie   56  Chicago

In [48]:
df.iloc[1]
# select index 1 for show row 1

Name        Bob
Age          34
City    Newyork
Name: first_runner_Up, dtype: object

In [38]:
df.loc['first_runner_Up']
# select label first_runner_Up for row 1

Age          34
City    Newyork
Name: first_runner_Up, dtype: object

In [ ]:
del df['City'] 
#  Delete City

KeyError: 'City'

In [56]:
df=df.drop(['Age'],axis=1)

In [57]:
df

                     Name
winner              Alice
first_runner_Up       Bob
second_runner_up  Charlie