In [58]:
import pandas as pd
data={
    "Name": ["Alice","Bob","Charlie"],
    "Age":[20,34,56],
    "City":["Indore","Newyork","Chicago"]
    }

In [59]:
df=pd.DataFrame(data) 
df

      Name  Age     City
0    Alice   20   Indore
1      Bob   34  Newyork
2  Charlie   56  Chicago

In [60]:
df[['Name','Age']] # Select Indiviual Columns

      Name  Age
0    Alice   20
1      Bob   34
2  Charlie   56

In [61]:
# Find Row detail of indexing 1 
# ! Work with Indexing
df.loc[1]

Name        Bob
Age          34
City    Newyork
Name: 1, dtype: object

In [62]:

df.iloc[1]

Name        Bob
Age          34
City    Newyork
Name: 1, dtype: object

In [63]:
# Show dataframe
df

      Name  Age     City
0    Alice   20   Indore
1      Bob   34  Newyork
2  Charlie   56  Chicago

In [64]:
# Change Indexing 0,1,2 to given index
df.index=['winner','first_runner_Up','second_runner_up']

In [65]:
df

                     Name  Age     City
winner              Alice   20   Indore
first_runner_Up       Bob   34  Newyork
second_runner_up  Charlie   56  Chicago

In [66]:
df.iloc[1]
# select index 1 for show row 1

Name        Bob
Age          34
City    Newyork
Name: first_runner_Up, dtype: object

In [67]:
df.loc['first_runner_Up']
# select label first_runner_Up for row 1

Name        Bob
Age          34
City    Newyork
Name: first_runner_Up, dtype: object

In [68]:

# ! Python specific  
del df['City'] 
#  Delete City

In [ ]:

# ! Pandas Method
df=df.drop(['Age'],axis=1)
# axis

In [80]:
df

                     NAME NAME UPPER
winner              Alice      ALICE
first_runner_Up       Bob        BOB
second_runner_up  Charlie    CHARLIE

In [72]:

# ! Rename Col Name
new_col={
    'Name':'NAME',
}
df.rename(columns=new_col,inplace=True)

df

                     NAME
winner              Alice
first_runner_Up       Bob
second_runner_up  Charlie

In [ ]:

# ! Uppercase for Name Column
uppercase_value=df['NAME'].str.upper()
uppercase_value

winner                ALICE
first_runner_Up         BOB
second_runner_up    CHARLIE
Name: NAME, dtype: object

In [78]:
df['NAME UPPER']=df['NAME'].str.upper()
df

                     NAME NAME UPPER
winner              Alice      ALICE
first_runner_Up       Bob        BOB
second_runner_up  Charlie    CHARLIE