In [330]:
import pandas as pd
data={
    "Name": ["Alice","Bob","Charlie"],
    "Age":[20,34,56],
    "City":["Indore","Newyork","Chicago"]
    }

In [331]:
df=pd.DataFrame(data) 
df

      Name  Age     City
0    Alice   20   Indore
1      Bob   34  Newyork
2  Charlie   56  Chicago

In [332]:
df[['Name','Age']] # Select Indiviual Columns

      Name  Age
0    Alice   20
1      Bob   34
2  Charlie   56

In [333]:
# Find Row detail of indexing 1 
# ! Work with Indexing
df.loc[1]

Name        Bob
Age          34
City    Newyork
Name: 1, dtype: object

In [334]:

df.iloc[1]

Name        Bob
Age          34
City    Newyork
Name: 1, dtype: object

In [335]:
# Show dataframe
df

      Name  Age     City
0    Alice   20   Indore
1      Bob   34  Newyork
2  Charlie   56  Chicago

In [336]:
# Change Indexing 0,1,2 to given index
df.index=['winner','first_runner_Up','second_runner_up']

In [337]:
df

                     Name  Age     City
winner              Alice   20   Indore
first_runner_Up       Bob   34  Newyork
second_runner_up  Charlie   56  Chicago

In [338]:
df.iloc[1]
# select index 1 for show row 1

Name        Bob
Age          34
City    Newyork
Name: first_runner_Up, dtype: object

In [339]:
df.loc['first_runner_Up']
# select label first_runner_Up for row 1

Name        Bob
Age          34
City    Newyork
Name: first_runner_Up, dtype: object

In [340]:

# ! Python specific  
del df['City'] 
#  Delete City

In [341]:

# ! Pandas Method
df=df.drop(['Age'],axis=1)
# axis

In [342]:
df

                     Name
winner              Alice
first_runner_Up       Bob
second_runner_up  Charlie

In [343]:

# ! Rename Col Name
new_col={
    'Name':'NAME',
}
df.rename(columns=new_col,inplace=True)

df

                     NAME
winner              Alice
first_runner_Up       Bob
second_runner_up  Charlie

In [344]:

# ! Uppercase for Name Column
uppercase_value=df['NAME'].str.upper()
uppercase_value

winner                ALICE
first_runner_Up         BOB
second_runner_up    CHARLIE
Name: NAME, dtype: object

In [345]:
df['NAME UPPER']=df['NAME'].str.upper()
df

                     NAME NAME UPPER
winner              Alice      ALICE
first_runner_Up       Bob        BOB
second_runner_up  Charlie    CHARLIE

Performing Data Analysis Over Some Random Data

In [346]:
data=pd.read_csv('data.csv')
data

      Name   Age     City    Position
0    Divya  23.0   Indore     Manager
1    Rohan  24.0    Dewas   Developer
2  Charlie   NaN  NewYork     Analyst
3      Bob  20.0  Chicago    Designer
4    Alice  17.0  Phoenix  Consultant

In [347]:

# ! Handling Missing Value  
# 1.isnull() for check 
data.isnull().sum()

Name        0
Age         1
City        0
Position    0
dtype: int64

In [348]:

#!Checking Notnull data 
data.notnull().sum()

Name        5
Age         4
City        5
Position    5
dtype: int64

In [349]:
data.dropna(axis=1)

      Name     City    Position
0    Divya   Indore     Manager
1    Rohan    Dewas   Developer
2  Charlie  NewYork     Analyst
3      Bob  Chicago    Designer
4    Alice  Phoenix  Consultant

Instead of dropping just fill values with actual values

In [350]:
data.fillna(0,inplace=True)
data

      Name   Age     City    Position
0    Divya  23.0   Indore     Manager
1    Rohan  24.0    Dewas   Developer
2  Charlie   0.0  NewYork     Analyst
3      Bob  20.0  Chicago    Designer
4    Alice  17.0  Phoenix  Consultant

In [351]:
data

      Name   Age     City    Position
0    Divya  23.0   Indore     Manager
1    Rohan  24.0    Dewas   Developer
2  Charlie   0.0  NewYork     Analyst
3      Bob  20.0  Chicago    Designer
4    Alice  17.0  Phoenix  Consultant

In [352]:
data.fillna(data['Age'].mean(),inplace=True)
data

      Name   Age     City    Position
0    Divya  23.0   Indore     Manager
1    Rohan  24.0    Dewas   Developer
2  Charlie   0.0  NewYork     Analyst
3      Bob  20.0  Chicago    Designer
4    Alice  17.0  Phoenix  Consultant

In [353]:
# Statistical Data
data.describe()

             Age
count   5.000000
mean   16.800000
std     9.782638
min     0.000000
25%    17.000000
50%    20.000000
75%    23.000000
max    24.000000

In [354]:
# Descriptive Statistics of the dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      object
 1   Age       5 non-null      float64
 2   City      5 non-null      object
 3   Position  5 non-null      object
dtypes: float64(1), object(3)
memory usage: 292.0+ bytes

In [355]:
# 1st 2 data
data.head(2)

    Name   Age    City   Position
0  Divya  23.0  Indore    Manager
1  Rohan  24.0   Dewas  Developer

In [356]:
# last 2 data
data.tail(2)

    Name   Age     City    Position
3    Bob  20.0  Chicago    Designer
4  Alice  17.0  Phoenix  Consultant

In [357]:
! pip install pandas

Requirement already satisfied: pandas in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\Divya Kumawat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [358]:
import pandas as pd

In [359]:
# Load the CSV File data 
df=pd.read_csv("data.csv")
df

      Name   Age     City    Position
0    Divya  23.0   Indore     Manager
1    Rohan  24.0    Dewas   Developer
2  Charlie   NaN  NewYork     Analyst
3      Bob  20.0  Chicago    Designer
4    Alice  17.0  Phoenix  Consultant

In [360]:
# Select Particular Multiple Columns
df[["Name","Age"]]

      Name   Age
0    Divya  23.0
1    Rohan  24.0
2  Charlie   NaN
3      Bob  20.0
4    Alice  17.0

In [361]:
#  Selecting a single row with help of index 
df.loc[1]

Name            Rohan
Age              24.0
City            Dewas
Position    Developer
Name: 1, dtype: object

In [362]:
#  Selecting a single row With help of position
df.iloc[1]

Name            Rohan
Age              24.0
City            Dewas
Position    Developer
Name: 1, dtype: object

## Setting Individual Column as a Index

In [363]:
# Change Index or Reindexing
# ! Selecting Index of the Dataframe to the 'Name' column
# ? inplace= True means Modify in Col
# df.set_index('Name',inplace=True)

In [364]:
df

      Name   Age     City    Position
0    Divya  23.0   Indore     Manager
1    Rohan  24.0    Dewas   Developer
2  Charlie   NaN  NewYork     Analyst
3      Bob  20.0  Chicago    Designer
4    Alice  17.0  Phoenix  Consultant

Setting New data as Index

In [365]:
df.index=['a','b','c','d','e']
df

      Name   Age     City    Position
a    Divya  23.0   Indore     Manager
b    Rohan  24.0    Dewas   Developer
c  Charlie   NaN  NewYork     Analyst
d      Bob  20.0  Chicago    Designer
e    Alice  17.0  Phoenix  Consultant

In [366]:
# Give data on the basis of Labels
df.loc['a']   #! Labels

Name          Divya
Age            23.0
City         Indore
Position    Manager
Name: a, dtype: object

In [367]:
#  Give data on the basis of Index

df.iloc[1]  #! Position

Name            Rohan
Age              24.0
City            Dewas
Position    Developer
Name: b, dtype: object

Deliting any Specific Column

In [368]:

# ! Python specific Method
# del df['City']

In [369]:
df

      Name   Age     City    Position
a    Divya  23.0   Indore     Manager
b    Rohan  24.0    Dewas   Developer
c  Charlie   NaN  NewYork     Analyst
d      Bob  20.0  Chicago    Designer
e    Alice  17.0  Phoenix  Consultant

Drop any Column

In [370]:

# ! Pandas Specifc Method
# Structure and Data will be delete
df.drop(['Age'],axis=1)

      Name     City    Position
a    Divya   Indore     Manager
b    Rohan    Dewas   Developer
c  Charlie  NewYork     Analyst
d      Bob  Chicago    Designer
e    Alice  Phoenix  Consultant

## Rename Column name

In [371]:
new_column={
    'Name':"NAME",
    'Age':"AGE"
}
# ! Rename columms named new_column and inplace= True means modify if only col is available
df.rename(columns=new_column,inplace=True)
df

      NAME   AGE     City    Position
a    Divya  23.0   Indore     Manager
b    Rohan  24.0    Dewas   Developer
c  Charlie   NaN  NewYork     Analyst
d      Bob  20.0  Chicago    Designer
e    Alice  17.0  Phoenix  Consultant

In [372]:
# Convert all Name in Upper case
# df["NAME"]=df['NAME'].str.upper()
df

      NAME   AGE     City    Position
a    Divya  23.0   Indore     Manager
b    Rohan  24.0    Dewas   Developer
c  Charlie   NaN  NewYork     Analyst
d      Bob  20.0  Chicago    Designer
e    Alice  17.0  Phoenix  Consultant

In [373]:
# Store Name Uppercase in different Column
df["NAME_Upper"]=df['NAME'].str.upper()
df

      NAME   AGE     City    Position NAME_Upper
a    Divya  23.0   Indore     Manager      DIVYA
b    Rohan  24.0    Dewas   Developer      ROHAN
c  Charlie   NaN  NewYork     Analyst    CHARLIE
d      Bob  20.0  Chicago    Designer        BOB
e    Alice  17.0  Phoenix  Consultant      ALICE

## Handles Missing Value

In [374]:
df.isnull().sum()

NAME          0
AGE           1
City          0
Position      0
NAME_Upper    0
dtype: int64

Delete or Drop row with null values

In [375]:
# Delete data In which value is missing
# df.dropna()

Delete or Drop Columns which has null Values

In [376]:

# ! Age Col is deleted because it have null values
# df.dropna(axis=1)

Replace a Null value with any value

In [ ]:
# Fill null valye by mean of the Age value
df.fillna(df['AGE'].mean(),inplace=True)
df

      NAME   AGE     City    Position NAME_Upper
a    Divya  23.0   Indore     Manager      DIVYA
b    Rohan  24.0    Dewas   Developer      ROHAN
c  Charlie  21.0  NewYork     Analyst    CHARLIE
d      Bob  20.0  Chicago    Designer        BOB
e    Alice  17.0  Phoenix  Consultant      ALICE

In [379]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   NAME        5 non-null      object
 1   AGE         5 non-null      float64
 2   City        5 non-null      object
 3   Position    5 non-null      object
 4   NAME_Upper  5 non-null      object
dtypes: float64(1), object(4)
memory usage: 412.0+ bytes

In [380]:
df.describe()

             AGE
count   5.000000
mean   21.000000
std     2.738613
min    17.000000
25%    20.000000
50%    21.000000
75%    23.000000
max    24.000000